/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import java.awt.Toolkit;
import main.accessDAL.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import main.Inicialdata.ControlerIntefazTabla;
import main.Inicialdata.InitialData;
import main.modelBL.AsesorComercial;
import main.modelBL.Campania;
import main.modelBL.CampaniaAplicada;
import main.modelBL.Consumo;
import main.modelBL.Libranza;
import main.modelBL.UsuarioModelBL;
import utils.ConnectionDB;

/**
 *
 * @author Germán García
 */
public class TabbedPane extends javax.swing.JFrame {

    private InitialData inicialdata = null;
    private ControlerIntefazTabla controlerIntefazTabla;
    public String usuarioAliasActual = null;

    /**
     * Creates new form TabbedPane
     */
    public TabbedPane() {
        initComponents();
        setIcon();
        iniciarVista2(this);
    }

    public void iniciarVista2(TabbedPane TabbedPane) {
        this.controlerIntefazTabla = new ControlerIntefazTabla(TabbedPane);
        controlerIntefazTabla.iniciarVista();
    }

    public void iniciarVista() {
        controlerIntefazTabla.iniciarVista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        panelLibranza = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneral1 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblGeneral2 = new javax.swing.JTable();
        lblGeneral1 = new javax.swing.JLabel();
        lblGeneral2 = new javax.swing.JLabel();
        panelCampania = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCampania = new javax.swing.JTable();
        btnCampaniaAgregar = new javax.swing.JButton();
        btnCampaniaEditar = new javax.swing.JButton();
        btnCampaniaBorrar = new javax.swing.JButton();
        btnCampaniaCancelar = new javax.swing.JButton();
        lblCampaniaID = new javax.swing.JLabel();
        txtCampaniaID = new javax.swing.JTextField();
        lblCampaniaDescripcion = new javax.swing.JLabel();
        txtCampaniaDescripcion = new javax.swing.JTextField();
        panelCampaniaAplicada = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCampaniaAplicada = new javax.swing.JTable();
        brnCampaniaAplicadaAgregar = new javax.swing.JButton();
        brnCampaniaAplicadaEditar = new javax.swing.JButton();
        brnCampaniaAplicadaBorrar = new javax.swing.JButton();
        brnCampaniaAplicadaCancelar = new javax.swing.JButton();
        lblCampaniaAplicadaID = new javax.swing.JLabel();
        lblCampaniaAplicadaAlias = new javax.swing.JLabel();
        lblCampaniaAplicadaCod = new javax.swing.JLabel();
        lblCampaniaAplicadaFecha = new javax.swing.JLabel();
        txtCampaniaAplicadaID = new javax.swing.JTextField();
        txtCampaniaAplicadaAlias = new javax.swing.JTextField();
        txtCampaniaAplicadaCod = new javax.swing.JTextField();
        txtCampaniaAplicadaFecha = new javax.swing.JTextField();
        panelConsumo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblConsumo = new javax.swing.JTable();
        btnConsumoAgregar = new javax.swing.JButton();
        btnConsumoEditar = new javax.swing.JButton();
        btnConsumoBorrar = new javax.swing.JButton();
        btnConsumoCancelar = new javax.swing.JButton();
        lblConsumoIDCa = new javax.swing.JLabel();
        lblConsumoAsesor = new javax.swing.JLabel();
        lblConsumoCuotas = new javax.swing.JLabel();
        lblConsumoTasa = new javax.swing.JLabel();
        txtConsumoIDCa = new javax.swing.JTextField();
        txtConsumoAsesor = new javax.swing.JTextField();
        txtConsumoCuotas = new javax.swing.JTextField();
        txtConsumoTasa = new javax.swing.JTextField();
        lblConsumoID = new javax.swing.JLabel();
        txtConsumoID = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLibranza = new javax.swing.JTable();
        btnLibranzaAgregar = new javax.swing.JButton();
        btnLibranzaEditar = new javax.swing.JButton();
        btnLibranzaBorrar = new javax.swing.JButton();
        btnLibranzaCancelar = new javax.swing.JButton();
        lblLibranzaIDCa = new javax.swing.JLabel();
        lblLibranzaEmpresa = new javax.swing.JLabel();
        txtLibranzaIDCa = new javax.swing.JTextField();
        txtLibranzaEmpresa = new javax.swing.JTextField();
        lblLibranzaPlazo = new javax.swing.JLabel();
        lblLibranzaTasa = new javax.swing.JLabel();
        txtLibranzaPlazo = new javax.swing.JTextField();
        txtLibranzaTasa = new javax.swing.JTextField();
        lblLibranzaID = new javax.swing.JLabel();
        txtLibranzaID = new javax.swing.JTextField();
        panelUsuario = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnUsuarioAgregar = new javax.swing.JButton();
        btnUsuarioEditar = new javax.swing.JButton();
        btnUsuarioBorrar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        lblUsuarioAlias = new javax.swing.JLabel();
        txtUsuarioAlias = new javax.swing.JTextField();
        lblUsuarioNombres = new javax.swing.JLabel();
        txtUsuarioNombres = new javax.swing.JTextField();
        lblUsuarioApellidos = new javax.swing.JLabel();
        txtUsuarioApellidos = new javax.swing.JTextField();
        lblUsuarioEmail = new javax.swing.JLabel();
        txtUsuarioEmail = new javax.swing.JTextField();
        lblUsuarioCelular = new javax.swing.JLabel();
        txtUsuarioCelular = new javax.swing.JTextField();
        lblUsuarioFecha = new javax.swing.JLabel();
        txtUsuarioFecha = new javax.swing.JTextField();
        lblUsuarioContrasena = new javax.swing.JLabel();
        txtUsuarioContrasena = new javax.swing.JTextField();
        panelAsesor = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblAsesor = new javax.swing.JTable();
        btnAsesorAgregar = new javax.swing.JButton();
        btnAsesorEditar = new javax.swing.JButton();
        btnAsesorBorrar = new javax.swing.JButton();
        btnAsesorCancelar = new javax.swing.JButton();
        lblAsesorID = new javax.swing.JLabel();
        lblAsesorNombres = new javax.swing.JLabel();
        lblAsesorApellidos = new javax.swing.JLabel();
        lblAsesorSucursal = new javax.swing.JLabel();
        txtAsesorNombres = new javax.swing.JTextField();
        txtAsesorID = new javax.swing.JTextField();
        txtAsesorSucursal = new javax.swing.JTextField();
        txtAsesorApellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnlineBank P5");
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fondo.png"))); // NOI18N

        tblGeneral1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGeneral1);

        tblGeneral2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblGeneral2);

        lblGeneral1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGeneral1.setText("Créditos de consumo aprobados");

        lblGeneral2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGeneral2.setText("Créditos de libranza aprobados");

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addComponent(jScrollPane8)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeneral1)
                    .addComponent(lblGeneral2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGeneral1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblGeneral2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );

        panelLibranza.addTab("Vista general", panelGeneral);

        tblCampania.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCampania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCampaniaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCampania);

        btnCampaniaAgregar.setText("Agregar");
        btnCampaniaAgregar.setFocusPainted(false);
        btnCampaniaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaniaAgregarActionPerformed(evt);
            }
        });

        btnCampaniaEditar.setText("Editar");
        btnCampaniaEditar.setFocusPainted(false);

        btnCampaniaBorrar.setText("Borrar");
        btnCampaniaBorrar.setFocusPainted(false);
        btnCampaniaBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCampaniaBorrarMouseClicked(evt);
            }
        });
        btnCampaniaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaniaBorrarActionPerformed(evt);
            }
        });

        btnCampaniaCancelar.setText("Cancelar");
        btnCampaniaCancelar.setFocusPainted(false);
        btnCampaniaCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaniaCancelarActionPerformed(evt);
            }
        });

        lblCampaniaID.setText("ID:");

        txtCampaniaID.setEditable(false);

        lblCampaniaDescripcion.setText("Descripción:");

        javax.swing.GroupLayout panelCampaniaLayout = new javax.swing.GroupLayout(panelCampania);
        panelCampania.setLayout(panelCampaniaLayout);
        panelCampaniaLayout.setHorizontalGroup(
            panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addGroup(panelCampaniaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCampaniaLayout.createSequentialGroup()
                        .addComponent(btnCampaniaAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCampaniaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCampaniaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCampaniaCancelar))
                    .addGroup(panelCampaniaLayout.createSequentialGroup()
                        .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelCampaniaLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblCampaniaID))
                            .addComponent(lblCampaniaDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampaniaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCampaniaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        panelCampaniaLayout.setVerticalGroup(
            panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCampaniaCancelar)
                    .addComponent(btnCampaniaBorrar)
                    .addComponent(btnCampaniaEditar)
                    .addComponent(btnCampaniaAgregar))
                .addGap(35, 35, 35)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaID)
                    .addComponent(txtCampaniaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaDescripcion)
                    .addComponent(txtCampaniaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 107, Short.MAX_VALUE))
        );

        panelLibranza.addTab("Campaña", panelCampania);

        tblCampaniaAplicada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCampaniaAplicada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCampaniaAplicadaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCampaniaAplicada);

        brnCampaniaAplicadaAgregar.setText("Agregar");
        brnCampaniaAplicadaAgregar.setFocusPainted(false);
        brnCampaniaAplicadaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCampaniaAplicadaAgregarActionPerformed(evt);
            }
        });

        brnCampaniaAplicadaEditar.setText("Editar");
        brnCampaniaAplicadaEditar.setFocusPainted(false);

        brnCampaniaAplicadaBorrar.setText("Borrar");
        brnCampaniaAplicadaBorrar.setFocusPainted(false);
        brnCampaniaAplicadaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCampaniaAplicadaBorrarActionPerformed(evt);
            }
        });

        brnCampaniaAplicadaCancelar.setText("Cancelar");
        brnCampaniaAplicadaCancelar.setFocusPainted(false);

        lblCampaniaAplicadaID.setText("ID:");

        lblCampaniaAplicadaAlias.setText("Alias usuario:");

        lblCampaniaAplicadaCod.setText("Código campaña:");

        lblCampaniaAplicadaFecha.setText("Fecha:");

        txtCampaniaAplicadaID.setEditable(false);

        javax.swing.GroupLayout panelCampaniaAplicadaLayout = new javax.swing.GroupLayout(panelCampaniaAplicada);
        panelCampaniaAplicada.setLayout(panelCampaniaAplicadaLayout);
        panelCampaniaAplicadaLayout.setHorizontalGroup(
            panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                        .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCampaniaAplicadaCod)
                            .addComponent(lblCampaniaAplicadaID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampaniaAplicadaAlias)
                            .addComponent(lblCampaniaAplicadaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampaniaAplicadaFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(txtCampaniaAplicadaCod)
                            .addComponent(txtCampaniaAplicadaAlias)
                            .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                                .addComponent(txtCampaniaAplicadaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                        .addComponent(brnCampaniaAplicadaAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brnCampaniaAplicadaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(brnCampaniaAplicadaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(brnCampaniaAplicadaCancelar)
                .addGap(35, 35, 35))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
        );
        panelCampaniaAplicadaLayout.setVerticalGroup(
            panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brnCampaniaAplicadaCancelar)
                    .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(brnCampaniaAplicadaAgregar)
                        .addComponent(brnCampaniaAplicadaEditar)
                        .addComponent(brnCampaniaAplicadaBorrar)))
                .addGap(35, 35, 35)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaID)
                    .addComponent(txtCampaniaAplicadaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaAlias)
                    .addComponent(txtCampaniaAplicadaAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaCod)
                    .addComponent(txtCampaniaAplicadaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaFecha)
                    .addComponent(txtCampaniaAplicadaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );

        panelLibranza.addTab("Campaña aplicada", panelCampaniaAplicada);

        tblConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsumoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblConsumo);

        btnConsumoAgregar.setText("Agregar");
        btnConsumoAgregar.setFocusPainted(false);
        btnConsumoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoAgregarActionPerformed(evt);
            }
        });

        btnConsumoEditar.setText("Editar");
        btnConsumoEditar.setFocusPainted(false);

        btnConsumoBorrar.setText("Borrar");
        btnConsumoBorrar.setFocusPainted(false);
        btnConsumoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsumoBorrarActionPerformed(evt);
            }
        });

        btnConsumoCancelar.setText("Cancelar");
        btnConsumoCancelar.setFocusPainted(false);

        lblConsumoIDCa.setText("ID campaña:");

        lblConsumoAsesor.setText("Asesor:");

        lblConsumoCuotas.setText("Cuotas:");

        lblConsumoTasa.setText("Tasa de interés:");

        txtConsumoIDCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumoIDCaActionPerformed(evt);
            }
        });

        txtConsumoCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsumoCuotasMouseClicked(evt);
            }
        });

        lblConsumoID.setText("ID:");

        txtConsumoID.setEditable(false);

        javax.swing.GroupLayout panelConsumoLayout = new javax.swing.GroupLayout(panelConsumo);
        panelConsumo.setLayout(panelConsumoLayout);
        panelConsumoLayout.setHorizontalGroup(
            panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(panelConsumoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsumoLayout.createSequentialGroup()
                        .addComponent(btnConsumoAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsumoEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsumoBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsumoCancelar))
                    .addGroup(panelConsumoLayout.createSequentialGroup()
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsumoLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lblConsumoID))
                            .addComponent(lblConsumoAsesor, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsumoID, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsumoAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblConsumoCuotas)
                            .addComponent(lblConsumoTasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsumoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConsumoTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(lblConsumoIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsumoIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        panelConsumoLayout.setVerticalGroup(
            panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsumoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsumoAgregar)
                    .addComponent(btnConsumoCancelar)
                    .addComponent(btnConsumoBorrar)
                    .addComponent(btnConsumoEditar))
                .addGap(66, 66, 66)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoCuotas)
                    .addComponent(txtConsumoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumoID)
                    .addComponent(txtConsumoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoAsesor)
                    .addComponent(lblConsumoTasa)
                    .addComponent(txtConsumoAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsumoTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConsumoIDCa)
                    .addComponent(txtConsumoIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        panelLibranza.addTab("Consumo", panelConsumo);

        tblLibranza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibranza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibranzaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblLibranza);

        btnLibranzaAgregar.setText("Agregar");
        btnLibranzaAgregar.setFocusPainted(false);
        btnLibranzaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibranzaAgregarActionPerformed(evt);
            }
        });

        btnLibranzaEditar.setText("Editar");
        btnLibranzaEditar.setFocusPainted(false);

        btnLibranzaBorrar.setText("Borrar");
        btnLibranzaBorrar.setFocusPainted(false);
        btnLibranzaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibranzaBorrarActionPerformed(evt);
            }
        });

        btnLibranzaCancelar.setText("Cancelar");
        btnLibranzaCancelar.setFocusPainted(false);

        lblLibranzaIDCa.setText("ID campaña:");

        lblLibranzaEmpresa.setText("Empresa:");

        lblLibranzaPlazo.setText("Meses plazo:");

        lblLibranzaTasa.setText("Tasa de interés:");

        lblLibranzaID.setText("ID:");

        txtLibranzaID.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnLibranzaAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLibranzaEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLibranzaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLibranzaCancelar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLibranzaEmpresa)
                            .addComponent(lblLibranzaID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLibranzaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibranzaID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLibranzaPlazo)
                            .addComponent(lblLibranzaTasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtLibranzaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(txtLibranzaTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLibranzaIDCa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLibranzaIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLibranzaCancelar)
                    .addComponent(btnLibranzaBorrar)
                    .addComponent(btnLibranzaEditar)
                    .addComponent(btnLibranzaAgregar))
                .addGap(66, 66, 66)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibranzaPlazo)
                    .addComponent(txtLibranzaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibranzaID)
                    .addComponent(txtLibranzaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibranzaEmpresa)
                    .addComponent(txtLibranzaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibranzaTasa)
                    .addComponent(txtLibranzaTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibranzaIDCa)
                    .addComponent(txtLibranzaIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );

        panelLibranza.addTab("Libranza", jPanel6);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblUsuario);

        btnUsuarioAgregar.setText("Agregar");
        btnUsuarioAgregar.setFocusPainted(false);
        btnUsuarioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioAgregarActionPerformed(evt);
            }
        });

        btnUsuarioEditar.setText("Editar");
        btnUsuarioEditar.setFocusPainted(false);

        btnUsuarioBorrar.setText("Borrar");
        btnUsuarioBorrar.setFocusPainted(false);
        btnUsuarioBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioBorrarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.setFocusPainted(false);

        lblUsuarioAlias.setText("Alias:");

        lblUsuarioNombres.setText("Nombres:");

        txtUsuarioNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioNombresActionPerformed(evt);
            }
        });

        lblUsuarioApellidos.setText("Apellidos:");

        lblUsuarioEmail.setText("Email:");

        lblUsuarioCelular.setText("Celular:");

        lblUsuarioFecha.setText("Fecha nacimiento:");

        lblUsuarioContrasena.setText("Contraseña:");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(btnUsuarioAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUsuarioEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUsuarioBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Cancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(lblUsuarioFecha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUsuarioFecha)
                                        .addGap(30, 30, 30)
                                        .addComponent(lblUsuarioContrasena))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblUsuarioNombres)
                                            .addComponent(lblUsuarioAlias)
                                            .addComponent(lblUsuarioEmail))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                                .addComponent(txtUsuarioAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtUsuarioEmail)
                                                    .addComponent(txtUsuarioNombres))
                                                .addGap(41, 41, 41)
                                                .addComponent(lblUsuarioApellidos)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuarioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuarioCelular)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cancelar)
                    .addComponent(btnUsuarioBorrar)
                    .addComponent(btnUsuarioEditar)
                    .addComponent(btnUsuarioAgregar))
                .addGap(35, 35, 35)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioAlias)
                    .addComponent(txtUsuarioAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioNombres)
                    .addComponent(txtUsuarioNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioApellidos)
                    .addComponent(txtUsuarioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioCelular)
                    .addComponent(txtUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioEmail))
                .addGap(26, 26, 26)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioFecha)
                    .addComponent(txtUsuarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioContrasena)
                    .addComponent(txtUsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        panelLibranza.addTab("Usuario", panelUsuario);

        tblAsesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAsesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsesorMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblAsesor);

        btnAsesorAgregar.setText("Agregar");
        btnAsesorAgregar.setFocusPainted(false);
        btnAsesorAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsesorAgregarActionPerformed(evt);
            }
        });

        btnAsesorEditar.setText("Editar");
        btnAsesorEditar.setFocusPainted(false);

        btnAsesorBorrar.setText("Borrar");
        btnAsesorBorrar.setFocusPainted(false);
        btnAsesorBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsesorBorrarMouseClicked(evt);
            }
        });
        btnAsesorBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsesorBorrarActionPerformed(evt);
            }
        });

        btnAsesorCancelar.setText("Cancelar");
        btnAsesorCancelar.setFocusPainted(false);

        lblAsesorID.setText("ID:");

        lblAsesorNombres.setText("Nombres:");

        lblAsesorApellidos.setText("Apellidos:");

        lblAsesorSucursal.setText("Sucursal:");

        txtAsesorID.setEditable(false);

        javax.swing.GroupLayout panelAsesorLayout = new javax.swing.GroupLayout(panelAsesor);
        panelAsesor.setLayout(panelAsesorLayout);
        panelAsesorLayout.setHorizontalGroup(
            panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(panelAsesorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsesorLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblAsesorID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAsesorID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(498, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAsesorLayout.createSequentialGroup()
                        .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAsesorLayout.createSequentialGroup()
                                .addComponent(btnAsesorAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsesorEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsesorBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAsesorCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsesorLayout.createSequentialGroup()
                                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsesorLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblAsesorSucursal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsesorSucursal))
                                    .addGroup(panelAsesorLayout.createSequentialGroup()
                                        .addComponent(lblAsesorNombres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAsesorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAsesorApellidos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsesorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
        );
        panelAsesorLayout.setVerticalGroup(
            panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsesorLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAsesorAgregar)
                    .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAsesorBorrar)
                        .addComponent(btnAsesorCancelar))
                    .addComponent(btnAsesorEditar))
                .addGap(35, 35, 35)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorID)
                    .addComponent(txtAsesorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorNombres)
                    .addComponent(lblAsesorApellidos)
                    .addComponent(txtAsesorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsesorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorSucursal)
                    .addComponent(txtAsesorSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        panelLibranza.addTab("Asesor comercial", panelAsesor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(panelLibranza)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblFondo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLibranza))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCampaniaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaniaAgregarActionPerformed
        Campania campaniaAgre = new Campania(0, txtCampaniaDescripcion.getText());
        CampaniaDAO campaniaDAO = new CampaniaDAO();
        campaniaDAO.AgregarCampania(campaniaAgre);
        iniciarVista();
        txtCampaniaID.setText("");
        txtCampaniaDescripcion.setText("");


    }//GEN-LAST:event_btnCampaniaAgregarActionPerformed

    private void txtConsumoIDCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumoIDCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumoIDCaActionPerformed

    private void btnLibranzaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibranzaAgregarActionPerformed
        String tassa = txtLibranzaTasa.getText();
        Libranza libranzaaAgre = new Libranza(0, Integer.parseInt(txtLibranzaIDCa.getText()), " ", txtLibranzaEmpresa.getText(), Integer.parseInt(txtLibranzaPlazo.getText()), (float) Float.parseFloat(tassa));
        LibranzaDAO libranzaDAO = new LibranzaDAO();
        libranzaDAO.AgregarLibranza(libranzaaAgre);

        iniciarVista();
        txtLibranzaID.setText("");
        txtLibranzaEmpresa.setText("");
        txtLibranzaIDCa.setText("");
        txtLibranzaPlazo.setText("");
        txtLibranzaTasa.setText("");


    }//GEN-LAST:event_btnLibranzaAgregarActionPerformed

    private void txtUsuarioNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioNombresActionPerformed

    private void btnUsuarioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioAgregarActionPerformed
        UsuarioModelBL usuarioModelBL = new UsuarioModelBL(txtUsuarioAlias.getText(), txtUsuarioNombres.getText(), txtUsuarioApellidos.getText(), txtUsuarioEmail.getText(), txtUsuarioCelular.getText(), txtUsuarioContrasena.getText(), txtUsuarioFecha.getText());
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.AgregarUsuario(usuarioModelBL);
        iniciarVista();
        txtUsuarioAlias.setText("");
        txtUsuarioNombres.setText("");
        txtUsuarioApellidos.setText("");
        txtUsuarioCelular.setText("");
        txtUsuarioContrasena.setText("");

        txtUsuarioEmail.setText("");
        txtUsuarioFecha.setText("");


    }//GEN-LAST:event_btnUsuarioAgregarActionPerformed

    private void tblCampaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCampaniaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtCampaniaID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtCampaniaDescripcion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            btnCampaniaBorrar.setEnabled(true);

        }

    }//GEN-LAST:event_tblCampaniaMouseClicked

    private void tblCampaniaAplicadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCampaniaAplicadaMouseClicked

        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtCampaniaAplicadaID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtCampaniaAplicadaCod.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtCampaniaAplicadaAlias.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtCampaniaAplicadaFecha.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            brnCampaniaAplicadaBorrar.setEnabled(true);
        }

    }//GEN-LAST:event_tblCampaniaAplicadaMouseClicked

    private void txtConsumoCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsumoCuotasMouseClicked

    }//GEN-LAST:event_txtConsumoCuotasMouseClicked

    private void tblConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsumoMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtConsumoID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtConsumoIDCa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            txtConsumoAsesor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtConsumoCuotas.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtConsumoTasa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            btnConsumoBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_tblConsumoMouseClicked

    private void tblLibranzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibranzaMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtLibranzaID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtLibranzaIDCa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtLibranzaEmpresa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtLibranzaPlazo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtLibranzaTasa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            btnLibranzaBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_tblLibranzaMouseClicked

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtUsuarioAlias.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtUsuarioNombres.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtUsuarioApellidos.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtUsuarioEmail.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtUsuarioCelular.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtUsuarioContrasena.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtUsuarioFecha.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            this.usuarioAliasActual = (receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            btnUsuarioBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void tblAsesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsesorMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtAsesorID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtAsesorNombres.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtAsesorApellidos.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtAsesorSucursal.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            btnAsesorBorrar.setEnabled(true);

        }
    }//GEN-LAST:event_tblAsesorMouseClicked

    private void btnAsesorBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsesorBorrarMouseClicked


    }//GEN-LAST:event_btnAsesorBorrarMouseClicked

    private void btnCampaniaBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCampaniaBorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCampaniaBorrarMouseClicked


    private void btnCampaniaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaniaBorrarActionPerformed
        int idcampania = Integer.parseInt(txtCampaniaID.getText());
        CampaniaDAO campaniaDAO = new CampaniaDAO();
        campaniaDAO.EliminarCampania(idcampania);
        iniciarVista();
        txtCampaniaID.setText("");
        txtCampaniaDescripcion.setText("");
        btnCampaniaBorrar.setEnabled(false);


    }//GEN-LAST:event_btnCampaniaBorrarActionPerformed

    private void brnCampaniaAplicadaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCampaniaAplicadaBorrarActionPerformed

        int idcampaniaApp = Integer.parseInt(txtCampaniaAplicadaID.getText());
        CampaniasAppDAO campaniasAppDAO = new CampaniasAppDAO();
        campaniasAppDAO.EliminarCampaniaApli(idcampaniaApp);
        iniciarVista();
        txtCampaniaAplicadaID.setText("");
        txtCampaniaAplicadaAlias.setText("");
        txtCampaniaAplicadaCod.setText("");
        txtCampaniaAplicadaFecha.setText("");
        brnCampaniaAplicadaBorrar.setEnabled(false);

    }//GEN-LAST:event_brnCampaniaAplicadaBorrarActionPerformed

    private void btnConsumoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoBorrarActionPerformed

        int idconsumo = Integer.parseInt(txtConsumoID.getText());
        ConsumoDAO consumoDAO = new ConsumoDAO();
        consumoDAO.EliminarConsumo(idconsumo);
        iniciarVista();
        txtConsumoAsesor.setText("");
        txtConsumoCuotas.setText("");
        txtConsumoIDCa.setText("");
        txtConsumoID.setText("");
        txtConsumoTasa.setText("");

        btnConsumoBorrar.setEnabled(false);
    }//GEN-LAST:event_btnConsumoBorrarActionPerformed

    private void btnLibranzaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibranzaBorrarActionPerformed
        int idlibranza = Integer.parseInt(txtLibranzaID.getText());
        LibranzaDAO libranzaDAO = new LibranzaDAO();
        libranzaDAO.EliminarLibranza(idlibranza);
        iniciarVista();
        txtLibranzaID.setText("");
        txtLibranzaEmpresa.setText("");
        txtLibranzaIDCa.setText("");
        txtLibranzaPlazo.setText("");
        txtLibranzaTasa.setText("");

        btnLibranzaBorrar.setEnabled(false);


    }//GEN-LAST:event_btnLibranzaBorrarActionPerformed

    private void btnUsuarioBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioBorrarActionPerformed
        // String AliasUsuario = txtUsuarioAlias.getText();
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.EliminarUsuario(usuarioAliasActual);
        iniciarVista();
        txtUsuarioAlias.setText("");
        txtUsuarioNombres.setText("");
        txtUsuarioApellidos.setText("");
        txtUsuarioCelular.setText("");
        txtUsuarioContrasena.setText("");

        txtUsuarioEmail.setText("");
        txtUsuarioFecha.setText("");

        btnUsuarioBorrar.setEnabled(false);


    }//GEN-LAST:event_btnUsuarioBorrarActionPerformed

    private void btnAsesorBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsesorBorrarActionPerformed
        int idAsesor = Integer.parseInt(txtAsesorID.getText());
        AsesorComercialDAO asesorComercialDAO = new AsesorComercialDAO();

        asesorComercialDAO.EliminaAsesorComercial(idAsesor);
        iniciarVista();
        txtAsesorID.setText("");
        txtAsesorApellidos.setText("");
        txtAsesorNombres.setText("");
        txtAsesorSucursal.setText("");
        btnAsesorBorrar.setEnabled(false);


    }//GEN-LAST:event_btnAsesorBorrarActionPerformed

    private void btnCampaniaCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaniaCancelarActionPerformed
        txtCampaniaID.setText("");
        txtCampaniaDescripcion.setText("");
        btnCampaniaBorrar.setEnabled(false);
    }//GEN-LAST:event_btnCampaniaCancelarActionPerformed

    private void brnCampaniaAplicadaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCampaniaAplicadaAgregarActionPerformed
        CampaniaAplicada campaniaAppAgre = new CampaniaAplicada(0, txtCampaniaAplicadaAlias.getText(), "", txtCampaniaAplicadaFecha.getText(), Integer.parseInt(txtCampaniaAplicadaCod.getText()), txtCampaniaAplicadaAlias.getText());
        CampaniasAppDAO campaniasAppDAO = new CampaniasAppDAO();
        campaniasAppDAO.AgregarCampaniaApli(campaniaAppAgre);
        iniciarVista();
        txtCampaniaAplicadaID.setText("");
        txtCampaniaAplicadaAlias.setText("");
        txtCampaniaAplicadaCod.setText("");
        txtCampaniaAplicadaFecha.setText("");


    }//GEN-LAST:event_brnCampaniaAplicadaAgregarActionPerformed

    private void btnConsumoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsumoAgregarActionPerformed

        Consumo consumoAgre = new Consumo(0, Integer.parseInt(txtConsumoIDCa.getText()), Integer.parseInt(txtConsumoCuotas.getText()), (float) Float.parseFloat(txtConsumoTasa.getText()), Integer.parseInt(txtConsumoAsesor.getText()));

        ConsumoDAO consumoDAO = new ConsumoDAO();
        consumoDAO.AgregarConsumo(consumoAgre);
        iniciarVista();

        txtConsumoAsesor.setText("");
        txtConsumoCuotas.setText("");
        txtConsumoIDCa.setText("");
        txtConsumoID.setText("");
        txtConsumoTasa.setText("");

    }//GEN-LAST:event_btnConsumoAgregarActionPerformed

    private void btnAsesorAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsesorAgregarActionPerformed
        AsesorComercial asesorComercial = new AsesorComercial(5,txtAsesorNombres.getText(), txtAsesorApellidos.getText(), txtAsesorSucursal.getText());
        AsesorComercialDAO asesorComercialDAO = new AsesorComercialDAO();
        asesorComercialDAO.AgregarAsesorcomercial(asesorComercial);
          iniciarVista();
        txtAsesorID.setText("");
        txtAsesorApellidos.setText("");
        txtAsesorNombres.setText("");
        txtAsesorSucursal.setText("");
        
    }//GEN-LAST:event_btnAsesorAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    public javax.swing.JButton brnCampaniaAplicadaAgregar;
    public javax.swing.JButton brnCampaniaAplicadaBorrar;
    private javax.swing.JButton brnCampaniaAplicadaCancelar;
    public javax.swing.JButton brnCampaniaAplicadaEditar;
    public javax.swing.JButton btnAsesorAgregar;
    public javax.swing.JButton btnAsesorBorrar;
    private javax.swing.JButton btnAsesorCancelar;
    public javax.swing.JButton btnAsesorEditar;
    public javax.swing.JButton btnCampaniaAgregar;
    public javax.swing.JButton btnCampaniaBorrar;
    private javax.swing.JButton btnCampaniaCancelar;
    public javax.swing.JButton btnCampaniaEditar;
    public javax.swing.JButton btnConsumoAgregar;
    public javax.swing.JButton btnConsumoBorrar;
    private javax.swing.JButton btnConsumoCancelar;
    public javax.swing.JButton btnConsumoEditar;
    public javax.swing.JButton btnLibranzaAgregar;
    public javax.swing.JButton btnLibranzaBorrar;
    private javax.swing.JButton btnLibranzaCancelar;
    public javax.swing.JButton btnLibranzaEditar;
    public javax.swing.JButton btnUsuarioAgregar;
    public javax.swing.JButton btnUsuarioBorrar;
    public javax.swing.JButton btnUsuarioEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblAsesorApellidos;
    private javax.swing.JLabel lblAsesorID;
    private javax.swing.JLabel lblAsesorNombres;
    private javax.swing.JLabel lblAsesorSucursal;
    private javax.swing.JLabel lblCampaniaAplicadaAlias;
    private javax.swing.JLabel lblCampaniaAplicadaCod;
    private javax.swing.JLabel lblCampaniaAplicadaFecha;
    private javax.swing.JLabel lblCampaniaAplicadaID;
    private javax.swing.JLabel lblCampaniaDescripcion;
    private javax.swing.JLabel lblCampaniaID;
    private javax.swing.JLabel lblConsumoAsesor;
    private javax.swing.JLabel lblConsumoCuotas;
    private javax.swing.JLabel lblConsumoID;
    private javax.swing.JLabel lblConsumoIDCa;
    private javax.swing.JLabel lblConsumoTasa;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblGeneral1;
    private javax.swing.JLabel lblGeneral2;
    private javax.swing.JLabel lblLibranzaEmpresa;
    private javax.swing.JLabel lblLibranzaID;
    private javax.swing.JLabel lblLibranzaIDCa;
    private javax.swing.JLabel lblLibranzaPlazo;
    private javax.swing.JLabel lblLibranzaTasa;
    private javax.swing.JLabel lblUsuarioAlias;
    private javax.swing.JLabel lblUsuarioApellidos;
    private javax.swing.JLabel lblUsuarioCelular;
    private javax.swing.JLabel lblUsuarioContrasena;
    private javax.swing.JLabel lblUsuarioEmail;
    private javax.swing.JLabel lblUsuarioFecha;
    private javax.swing.JLabel lblUsuarioNombres;
    private javax.swing.JPanel panelAsesor;
    private javax.swing.JPanel panelCampania;
    private javax.swing.JPanel panelCampaniaAplicada;
    private javax.swing.JPanel panelConsumo;
    private javax.swing.JPanel panelGeneral;
    public javax.swing.JTabbedPane panelLibranza;
    private javax.swing.JPanel panelUsuario;
    public javax.swing.JTable tblAsesor;
    public javax.swing.JTable tblCampania;
    public javax.swing.JTable tblCampaniaAplicada;
    public javax.swing.JTable tblConsumo;
    public javax.swing.JTable tblGeneral1;
    public javax.swing.JTable tblGeneral2;
    public javax.swing.JTable tblLibranza;
    public javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtAsesorApellidos;
    private javax.swing.JTextField txtAsesorID;
    private javax.swing.JTextField txtAsesorNombres;
    private javax.swing.JTextField txtAsesorSucursal;
    private javax.swing.JTextField txtCampaniaAplicadaAlias;
    private javax.swing.JTextField txtCampaniaAplicadaCod;
    private javax.swing.JTextField txtCampaniaAplicadaFecha;
    private javax.swing.JTextField txtCampaniaAplicadaID;
    private javax.swing.JTextField txtCampaniaDescripcion;
    private javax.swing.JTextField txtCampaniaID;
    private javax.swing.JTextField txtConsumoAsesor;
    private javax.swing.JTextField txtConsumoCuotas;
    private javax.swing.JTextField txtConsumoID;
    private javax.swing.JTextField txtConsumoIDCa;
    private javax.swing.JTextField txtConsumoTasa;
    private javax.swing.JTextField txtLibranzaEmpresa;
    public javax.swing.JTextField txtLibranzaID;
    private javax.swing.JTextField txtLibranzaIDCa;
    private javax.swing.JTextField txtLibranzaPlazo;
    private javax.swing.JTextField txtLibranzaTasa;
    private javax.swing.JTextField txtUsuarioAlias;
    private javax.swing.JTextField txtUsuarioApellidos;
    private javax.swing.JTextField txtUsuarioCelular;
    private javax.swing.JTextField txtUsuarioContrasena;
    private javax.swing.JTextField txtUsuarioEmail;
    private javax.swing.JTextField txtUsuarioFecha;
    private javax.swing.JTextField txtUsuarioNombres;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
    }

}
