/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main.view;

import java.awt.Toolkit;
import main.accessDAL.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import main.Inicialdata.ControlerIntefazTabla;
import main.Inicialdata.InitialData;
import main.modelBL.AsesorComercial;
import main.modelBL.Campania;
import main.modelBL.CampaniaAplicada;
import main.modelBL.Consumo;
import main.modelBL.Libranza;
import main.modelBL.UsuarioModelBL;
import utils.ConnectionDB;

/**
 *
 * @author Germán y Lady
 */
public class TabbedPane extends javax.swing.JFrame {
    
    
    private InitialData inicialdata = null;
    private JTable tblResultadosUsuaros;
    private JTable tblResultadoscampania;
    private JTable tblResultadoscampaniasAplicadas;
    private JTable tblResultadoConsumo;
    private JTable tblResultadoAsesor;
    private JTable tblResultadolibraza;
    private JTable tblResultadoGeneral;
    private JTable tblResultadoGeneral2;

    /**
     * Creates new form TabbedPane
     */
    public TabbedPane() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLibranza = new javax.swing.JTabbedPane();
        panelGeneral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGeneral1 = new javax.swing.JTable();
        btnGeneralActualizar = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblGeneral2 = new javax.swing.JTable();
        panelCampania = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCampania = new javax.swing.JTable();
        btnCampaniaAgregar = new javax.swing.JButton();
        btnCampaniaEditar = new javax.swing.JButton();
        btnCampaniaBorrar = new javax.swing.JButton();
        btnCampaniaCancelar = new javax.swing.JButton();
        lblCampaniaID = new javax.swing.JLabel();
        txtCampaniaID = new javax.swing.JTextField();
        lblCampaniaDescripcion = new javax.swing.JLabel();
        txtCampaniaDescripcion = new javax.swing.JTextField();
        panelCampaniaAplicada = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCampaniaAplicada = new javax.swing.JTable();
        brnCampaniaAplicadaAgregar = new javax.swing.JButton();
        brnCampaniaAplicadaEditar = new javax.swing.JButton();
        brnCampaniaAplicadaBorrar = new javax.swing.JButton();
        brnCampaniaAplicadaCancelar = new javax.swing.JButton();
        lblCampaniaAplicadaID = new javax.swing.JLabel();
        lblCampaniaAplicadaAlias = new javax.swing.JLabel();
        lblCampaniaAplicadaCod = new javax.swing.JLabel();
        lblCampaniaAplicadaFecha = new javax.swing.JLabel();
        txtCampaniaAplicadaID = new javax.swing.JTextField();
        txtCampaniaAplicadaAlias = new javax.swing.JTextField();
        txtCampaniaAplicadaCod = new javax.swing.JTextField();
        txtCampaniaAplicadaFecha = new javax.swing.JTextField();
        panelConsumo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblConsumo = new javax.swing.JTable();
        btnConsumoAgregar = new javax.swing.JButton();
        btnConsumoEditar = new javax.swing.JButton();
        btnConsumoBorrar = new javax.swing.JButton();
        btnConsumoCancelar = new javax.swing.JButton();
        lblConsumoID = new javax.swing.JLabel();
        lblConsumoAsesor = new javax.swing.JLabel();
        lblConsumoCuotas = new javax.swing.JLabel();
        lblConsumoTasa = new javax.swing.JLabel();
        txtConsumoIDCa = new javax.swing.JTextField();
        txtConsumoAsesor = new javax.swing.JTextField();
        txtConsumoCuotas = new javax.swing.JTextField();
        txtConsumoTasa = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLibranza = new javax.swing.JTable();
        btnLibranzaAgregar = new javax.swing.JButton();
        btnLibranzaEditar = new javax.swing.JButton();
        btnLibranzaBorrar = new javax.swing.JButton();
        btnLibranzaCancelar = new javax.swing.JButton();
        lblLibranzaID = new javax.swing.JLabel();
        lblLibranzaEmpresa = new javax.swing.JLabel();
        txtLibranzaIDCa = new javax.swing.JTextField();
        txtLibranzaEmpresa = new javax.swing.JTextField();
        lblLibranzaPlazo = new javax.swing.JLabel();
        lblLibranzaTasa = new javax.swing.JLabel();
        txtLibranzaPlazo = new javax.swing.JTextField();
        txtLibranzaTasa = new javax.swing.JTextField();
        panelUsuario = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        btnUsuarioAgregar = new javax.swing.JButton();
        btnUsuarioEditar = new javax.swing.JButton();
        btnUsuarioBorrar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        lblUsuarioAlias = new javax.swing.JLabel();
        txtUsuarioAlias = new javax.swing.JTextField();
        lblUsuarioNombres = new javax.swing.JLabel();
        txtUsuarioNombres = new javax.swing.JTextField();
        lblUsuarioApellidos = new javax.swing.JLabel();
        txtUsuarioApellidos = new javax.swing.JTextField();
        lblUsuarioEmail = new javax.swing.JLabel();
        txtUsuarioEmail = new javax.swing.JTextField();
        lblUsuarioCelular = new javax.swing.JLabel();
        txtUsuarioCelular = new javax.swing.JTextField();
        lblUsuarioFecha = new javax.swing.JLabel();
        txtUsuarioFecha = new javax.swing.JTextField();
        lblUsuarioContrasena = new javax.swing.JLabel();
        txtUsuarioContrasena = new javax.swing.JTextField();
        panelAsesor = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblAsesor = new javax.swing.JTable();
        btnAsesorAgregar = new javax.swing.JButton();
        btnAsesorEditar = new javax.swing.JButton();
        btnAsesorBorrar = new javax.swing.JButton();
        btnAsesorCancelar = new javax.swing.JButton();
        lblAsesorID = new javax.swing.JLabel();
        lblAsesorNombres = new javax.swing.JLabel();
        lblAsesorApellidos = new javax.swing.JLabel();
        lblAsesorSucursal = new javax.swing.JLabel();
        txtAsesorNombres = new javax.swing.JTextField();
        txtAsesorID = new javax.swing.JTextField();
        txtAsesorSucursal = new javax.swing.JTextField();
        txtAsesorApellidos = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("OnlineBank P5");
        setIconImage(getIconImage());
        setIconImages(getIconImages());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        tblGeneral1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblGeneral1);

        btnGeneralActualizar.setText("Actualizar");

        tblGeneral2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(tblGeneral2);

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGeneralActualizar)
                .addGap(253, 253, 253))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
            .addComponent(jScrollPane8)
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeneralActualizar)
                .addContainerGap())
        );

        panelLibranza.addTab("Vista general", panelGeneral);

        tblCampania.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCampania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCampaniaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCampania);

        btnCampaniaAgregar.setText("Agregar");
        btnCampaniaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaniaAgregarActionPerformed(evt);
            }
        });

        btnCampaniaEditar.setText("Editar");

        btnCampaniaBorrar.setText("Borrar");
        btnCampaniaBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCampaniaBorrarMouseClicked(evt);
            }
        });
        btnCampaniaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaniaBorrarActionPerformed(evt);
            }
        });

        btnCampaniaCancelar.setText("Cancelar");

        lblCampaniaID.setText("ID:");

        lblCampaniaDescripcion.setText("Descripción:");

        javax.swing.GroupLayout panelCampaniaLayout = new javax.swing.GroupLayout(panelCampania);
        panelCampania.setLayout(panelCampaniaLayout);
        panelCampaniaLayout.setHorizontalGroup(
            panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(panelCampaniaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCampaniaLayout.createSequentialGroup()
                        .addComponent(btnCampaniaAgregar)
                        .addGap(94, 94, 94)
                        .addComponent(btnCampaniaEditar)
                        .addGap(86, 86, 86)
                        .addComponent(btnCampaniaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(btnCampaniaCancelar))
                    .addGroup(panelCampaniaLayout.createSequentialGroup()
                        .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCampaniaID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampaniaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampaniaID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCampaniaDescripcion))))
                .addGap(36, 36, 36))
        );
        panelCampaniaLayout.setVerticalGroup(
            panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCampaniaAgregar)
                    .addComponent(btnCampaniaEditar)
                    .addComponent(btnCampaniaBorrar)
                    .addComponent(btnCampaniaCancelar))
                .addGap(18, 18, 18)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaID)
                    .addComponent(txtCampaniaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCampaniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaDescripcion)
                    .addComponent(txtCampaniaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        panelLibranza.addTab("Campaña", panelCampania);

        tblCampaniaAplicada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCampaniaAplicada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCampaniaAplicadaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCampaniaAplicada);

        brnCampaniaAplicadaAgregar.setText("Agregar");

        brnCampaniaAplicadaEditar.setText("Editar");

        brnCampaniaAplicadaBorrar.setText("Borrar");

        brnCampaniaAplicadaCancelar.setText("Cancelar");

        lblCampaniaAplicadaID.setText("ID:");

        lblCampaniaAplicadaAlias.setText("Alias usuario:");

        lblCampaniaAplicadaCod.setText("Código campaña:");

        lblCampaniaAplicadaFecha.setText("Fecha:");

        javax.swing.GroupLayout panelCampaniaAplicadaLayout = new javax.swing.GroupLayout(panelCampaniaAplicada);
        panelCampaniaAplicada.setLayout(panelCampaniaAplicadaLayout);
        panelCampaniaAplicadaLayout.setHorizontalGroup(
            panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                        .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCampaniaAplicadaCod)
                            .addComponent(lblCampaniaAplicadaID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampaniaAplicadaAlias)
                            .addComponent(lblCampaniaAplicadaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCampaniaAplicadaFecha)
                            .addComponent(txtCampaniaAplicadaCod)
                            .addComponent(txtCampaniaAplicadaAlias)
                            .addComponent(txtCampaniaAplicadaID)))
                    .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                        .addComponent(brnCampaniaAplicadaAgregar)
                        .addGap(77, 77, 77)
                        .addComponent(brnCampaniaAplicadaEditar)))
                .addGap(66, 66, 66)
                .addComponent(brnCampaniaAplicadaBorrar)
                .addGap(77, 77, 77)
                .addComponent(brnCampaniaAplicadaCancelar)
                .addGap(60, 60, 60))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panelCampaniaAplicadaLayout.setVerticalGroup(
            panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCampaniaAplicadaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brnCampaniaAplicadaEditar)
                    .addComponent(brnCampaniaAplicadaBorrar)
                    .addComponent(brnCampaniaAplicadaAgregar)
                    .addComponent(brnCampaniaAplicadaCancelar))
                .addGap(17, 17, 17)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaID)
                    .addComponent(txtCampaniaAplicadaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaAlias)
                    .addComponent(txtCampaniaAplicadaAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaCod)
                    .addComponent(txtCampaniaAplicadaCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCampaniaAplicadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCampaniaAplicadaFecha)
                    .addComponent(txtCampaniaAplicadaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        panelLibranza.addTab("Campaña aplicada", panelCampaniaAplicada);

        tblConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblConsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsumoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblConsumo);

        btnConsumoAgregar.setText("Agregar");

        btnConsumoEditar.setText("Editar");

        btnConsumoBorrar.setText("Borrar");

        btnConsumoCancelar.setText("Cancelar");

        lblConsumoID.setText("ID CAMPAÑA:");

        lblConsumoAsesor.setText("Asesor:");

        lblConsumoCuotas.setText("Cuotas:");

        lblConsumoTasa.setText("Tasa de interés:");

        txtConsumoIDCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumoIDCaActionPerformed(evt);
            }
        });

        txtConsumoCuotas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsumoCuotasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelConsumoLayout = new javax.swing.GroupLayout(panelConsumo);
        panelConsumo.setLayout(panelConsumoLayout);
        panelConsumoLayout.setHorizontalGroup(
            panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(panelConsumoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsumoLayout.createSequentialGroup()
                        .addComponent(btnConsumoAgregar)
                        .addGap(75, 75, 75)
                        .addComponent(btnConsumoEditar)
                        .addGap(80, 80, 80)
                        .addComponent(btnConsumoBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                        .addComponent(btnConsumoCancelar)
                        .addGap(34, 34, 34))
                    .addGroup(panelConsumoLayout.createSequentialGroup()
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConsumoAsesor)
                            .addComponent(lblConsumoID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConsumoIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelConsumoLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtConsumoAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88)
                        .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelConsumoLayout.createSequentialGroup()
                                .addComponent(lblConsumoTasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtConsumoTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelConsumoLayout.createSequentialGroup()
                                .addComponent(lblConsumoCuotas)
                                .addGap(47, 47, 47)
                                .addComponent(txtConsumoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelConsumoLayout.setVerticalGroup(
            panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsumoLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsumoEditar)
                    .addComponent(btnConsumoAgregar)
                    .addComponent(btnConsumoBorrar)
                    .addComponent(btnConsumoCancelar))
                .addGap(28, 28, 28)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoID)
                    .addComponent(lblConsumoCuotas)
                    .addComponent(txtConsumoIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsumoCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(panelConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConsumoAsesor)
                    .addComponent(lblConsumoTasa)
                    .addComponent(txtConsumoAsesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsumoTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        panelLibranza.addTab("Consumo", panelConsumo);

        tblLibranza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblLibranza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLibranzaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblLibranza);

        btnLibranzaAgregar.setText("Agregar");
        btnLibranzaAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibranzaAgregarActionPerformed(evt);
            }
        });

        btnLibranzaEditar.setText("Editar");

        btnLibranzaBorrar.setText("Borrar");

        btnLibranzaCancelar.setText("Cancelar");

        lblLibranzaID.setText("ID CAMPAÑA:");

        lblLibranzaEmpresa.setText("Empresa:");

        lblLibranzaPlazo.setText("Meses plazo:");

        lblLibranzaTasa.setText("Tasa de interés:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnLibranzaAgregar)
                        .addGap(86, 86, 86)
                        .addComponent(btnLibranzaEditar)
                        .addGap(76, 76, 76)
                        .addComponent(btnLibranzaBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(btnLibranzaCancelar)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLibranzaEmpresa)
                            .addComponent(lblLibranzaID, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtLibranzaIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtLibranzaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLibranzaPlazo)
                            .addComponent(lblLibranzaTasa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLibranzaTasa, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLibranzaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLibranzaAgregar)
                    .addComponent(btnLibranzaEditar)
                    .addComponent(btnLibranzaBorrar)
                    .addComponent(btnLibranzaCancelar))
                .addGap(31, 31, 31)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibranzaID)
                    .addComponent(txtLibranzaIDCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibranzaPlazo)
                    .addComponent(txtLibranzaPlazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibranzaEmpresa)
                    .addComponent(txtLibranzaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLibranzaTasa)
                    .addComponent(txtLibranzaTasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        panelLibranza.addTab("Libranza", jPanel6);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblUsuario);

        btnUsuarioAgregar.setText("Agregar");
        btnUsuarioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioAgregarActionPerformed(evt);
            }
        });

        btnUsuarioEditar.setText("Editar");

        btnUsuarioBorrar.setText("Borrar");

        Cancelar.setText("Cancelar");

        lblUsuarioAlias.setText("Alias:");

        lblUsuarioNombres.setText("Nombres:");

        txtUsuarioNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioNombresActionPerformed(evt);
            }
        });

        lblUsuarioApellidos.setText("Apellidos:");

        lblUsuarioEmail.setText("Email:");

        lblUsuarioCelular.setText("Celular:");

        lblUsuarioFecha.setText("Fecha nacimiento:");

        lblUsuarioContrasena.setText("Contraseña:");

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addComponent(lblUsuarioFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(lblUsuarioNombres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(24, 24, 24))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblUsuarioAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(55, 55, 55)))
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addComponent(txtUsuarioAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsuarioEmail)
                                            .addComponent(txtUsuarioNombres))
                                        .addGap(41, 41, 41)
                                        .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelUsuarioLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(lblUsuarioCelular))
                                            .addComponent(lblUsuarioApellidos)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(lblUsuarioContrasena)
                                        .addGap(1, 1, 1)))
                                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuarioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuarioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44))
                    .addGroup(panelUsuarioLayout.createSequentialGroup()
                        .addComponent(btnUsuarioAgregar)
                        .addGap(53, 53, 53)
                        .addComponent(btnUsuarioEditar)
                        .addGap(57, 57, 57)
                        .addComponent(btnUsuarioBorrar)
                        .addGap(49, 49, 49)
                        .addComponent(Cancelar)
                        .addContainerGap(179, Short.MAX_VALUE))))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuarioAgregar)
                    .addComponent(btnUsuarioEditar)
                    .addComponent(btnUsuarioBorrar)
                    .addComponent(Cancelar))
                .addGap(21, 21, 21)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioAlias)
                    .addComponent(txtUsuarioAlias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioNombres)
                    .addComponent(txtUsuarioNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioApellidos)
                    .addComponent(txtUsuarioApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioCelular)
                    .addComponent(txtUsuarioEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioEmail))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioFecha)
                    .addComponent(txtUsuarioFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioContrasena)
                    .addComponent(txtUsuarioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        panelLibranza.addTab("Usuario", panelUsuario);

        tblAsesor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAsesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsesorMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblAsesor);

        btnAsesorAgregar.setText("Agregar");

        btnAsesorEditar.setText("Editar");

        btnAsesorBorrar.setText("Borrar");
        btnAsesorBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAsesorBorrarMouseClicked(evt);
            }
        });

        btnAsesorCancelar.setText("Cancelar");

        lblAsesorID.setText("ID:");

        lblAsesorNombres.setText("Nombres:");

        lblAsesorApellidos.setText("Apellidos:");

        lblAsesorSucursal.setText("Sucursal:");

        javax.swing.GroupLayout panelAsesorLayout = new javax.swing.GroupLayout(panelAsesor);
        panelAsesor.setLayout(panelAsesorLayout);
        panelAsesorLayout.setHorizontalGroup(
            panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7)
            .addGroup(panelAsesorLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsesorLayout.createSequentialGroup()
                        .addComponent(lblAsesorID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAsesorID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAsesorLayout.createSequentialGroup()
                        .addComponent(btnAsesorAgregar)
                        .addGap(80, 80, 80)
                        .addComponent(btnAsesorEditar)
                        .addGap(70, 70, 70)
                        .addComponent(btnAsesorBorrar)
                        .addGap(58, 58, 58)
                        .addComponent(btnAsesorCancelar))
                    .addGroup(panelAsesorLayout.createSequentialGroup()
                        .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAsesorLayout.createSequentialGroup()
                                .addComponent(lblAsesorSucursal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAsesorSucursal))
                            .addGroup(panelAsesorLayout.createSequentialGroup()
                                .addComponent(lblAsesorNombres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAsesorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAsesorApellidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAsesorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelAsesorLayout.setVerticalGroup(
            panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsesorLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsesorAgregar)
                    .addComponent(btnAsesorEditar)
                    .addComponent(btnAsesorBorrar)
                    .addComponent(btnAsesorCancelar))
                .addGap(25, 25, 25)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorID)
                    .addComponent(txtAsesorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorNombres)
                    .addComponent(lblAsesorApellidos)
                    .addComponent(txtAsesorNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsesorApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(panelAsesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsesorSucursal)
                    .addComponent(txtAsesorSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        panelLibranza.addTab("Asesor comercial", panelAsesor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLibranza)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panelLibranza))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCampaniaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaniaAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCampaniaAgregarActionPerformed

    private void txtConsumoIDCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumoIDCaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumoIDCaActionPerformed

    private void btnLibranzaAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibranzaAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibranzaAgregarActionPerformed

    private void txtUsuarioNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioNombresActionPerformed

    private void btnUsuarioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioAgregarActionPerformed
        // TODO add your handling code here:
        UsuarioDAO usuarioDAO = new UsuarioDAO();
        usuarioDAO.AgregarGerman("insert into usuario values ('dragnslav3', 'german', 'garcia', 'dragnslav3@gmail.com', '3008281940', 'admin', '21/09/1981');");

        /*
        Connection conn=ConnectionDB.getConnection();
        
        
        
        try {
            PreparedStatement prepared = conn.prepareStatement("insert into usuario values ('dragnslav3', 'german', 'garcia', 'dragnslav3@gmail.com', '3008281940', 'admin', '21/09/1981');");
            prepared.execute();
            System.out.println("Usuario Agregado");
        } catch (Exception e) {
            System.out.println(e);
        }*/
    }//GEN-LAST:event_btnUsuarioAgregarActionPerformed

    private void tblCampaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCampaniaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtCampaniaID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtCampaniaDescripcion.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());

        }

    }//GEN-LAST:event_tblCampaniaMouseClicked

    private void tblCampaniaAplicadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCampaniaAplicadaMouseClicked

        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtCampaniaAplicadaID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtCampaniaAplicadaCod.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtCampaniaAplicadaAlias.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtCampaniaAplicadaFecha.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());

        }

    }//GEN-LAST:event_tblCampaniaAplicadaMouseClicked

    private void txtConsumoCuotasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsumoCuotasMouseClicked

    }//GEN-LAST:event_txtConsumoCuotasMouseClicked

    private void tblConsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsumoMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtConsumoIDCa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());
            txtConsumoAsesor.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtConsumoCuotas.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtConsumoTasa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());

        }
    }//GEN-LAST:event_tblConsumoMouseClicked

    private void tblLibranzaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLibranzaMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtLibranzaIDCa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtLibranzaEmpresa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtLibranzaPlazo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtLibranzaTasa.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_tblLibranzaMouseClicked

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtUsuarioAlias.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtUsuarioNombres.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtUsuarioApellidos.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtUsuarioEmail.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
            txtUsuarioCelular.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 4).toString());
            txtUsuarioContrasena.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 5).toString());
            txtUsuarioFecha.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 6).toString());

        }
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void tblAsesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsesorMouseClicked
       if (evt.getClickCount() == 1) {
            JTable receptor = (JTable) evt.getSource();
            txtAsesorID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 0).toString());
            txtAsesorNombres.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 1).toString());
            txtAsesorApellidos.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 2).toString());
            txtAsesorSucursal.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(), 3).toString());
           

        }
    }//GEN-LAST:event_tblAsesorMouseClicked

    private void btnAsesorBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAsesorBorrarMouseClicked
       
        
    }//GEN-LAST:event_btnAsesorBorrarMouseClicked

    private void btnCampaniaBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCampaniaBorrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCampaniaBorrarMouseClicked

    
    private void btnCampaniaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaniaBorrarActionPerformed
        int idcampania = Integer.parseInt(txtCampaniaID.getText());
        CampaniaDAO campaniaDAO = new CampaniaDAO();
        campaniaDAO.EliminarCampania(idcampania);
        iniciarVista();
        
       
    }//GEN-LAST:event_btnCampaniaBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedPane().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton brnCampaniaAplicadaAgregar;
    private javax.swing.JButton brnCampaniaAplicadaBorrar;
    private javax.swing.JButton brnCampaniaAplicadaCancelar;
    private javax.swing.JButton brnCampaniaAplicadaEditar;
    private javax.swing.JButton btnAsesorAgregar;
    private javax.swing.JButton btnAsesorBorrar;
    private javax.swing.JButton btnAsesorCancelar;
    private javax.swing.JButton btnAsesorEditar;
    private javax.swing.JButton btnCampaniaAgregar;
    private javax.swing.JButton btnCampaniaBorrar;
    private javax.swing.JButton btnCampaniaCancelar;
    private javax.swing.JButton btnCampaniaEditar;
    private javax.swing.JButton btnConsumoAgregar;
    private javax.swing.JButton btnConsumoBorrar;
    private javax.swing.JButton btnConsumoCancelar;
    private javax.swing.JButton btnConsumoEditar;
    private javax.swing.JButton btnGeneralActualizar;
    private javax.swing.JButton btnLibranzaAgregar;
    private javax.swing.JButton btnLibranzaBorrar;
    private javax.swing.JButton btnLibranzaCancelar;
    private javax.swing.JButton btnLibranzaEditar;
    private javax.swing.JButton btnUsuarioAgregar;
    private javax.swing.JButton btnUsuarioBorrar;
    private javax.swing.JButton btnUsuarioEditar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JLabel lblAsesorApellidos;
    private javax.swing.JLabel lblAsesorID;
    private javax.swing.JLabel lblAsesorNombres;
    private javax.swing.JLabel lblAsesorSucursal;
    private javax.swing.JLabel lblCampaniaAplicadaAlias;
    private javax.swing.JLabel lblCampaniaAplicadaCod;
    private javax.swing.JLabel lblCampaniaAplicadaFecha;
    private javax.swing.JLabel lblCampaniaAplicadaID;
    private javax.swing.JLabel lblCampaniaDescripcion;
    private javax.swing.JLabel lblCampaniaID;
    private javax.swing.JLabel lblConsumoAsesor;
    private javax.swing.JLabel lblConsumoCuotas;
    private javax.swing.JLabel lblConsumoID;
    private javax.swing.JLabel lblConsumoTasa;
    private javax.swing.JLabel lblLibranzaEmpresa;
    private javax.swing.JLabel lblLibranzaID;
    private javax.swing.JLabel lblLibranzaPlazo;
    private javax.swing.JLabel lblLibranzaTasa;
    private javax.swing.JLabel lblUsuarioAlias;
    private javax.swing.JLabel lblUsuarioApellidos;
    private javax.swing.JLabel lblUsuarioCelular;
    private javax.swing.JLabel lblUsuarioContrasena;
    private javax.swing.JLabel lblUsuarioEmail;
    private javax.swing.JLabel lblUsuarioFecha;
    private javax.swing.JLabel lblUsuarioNombres;
    private javax.swing.JPanel panelAsesor;
    private javax.swing.JPanel panelCampania;
    private javax.swing.JPanel panelCampaniaAplicada;
    private javax.swing.JPanel panelConsumo;
    private javax.swing.JPanel panelGeneral;
    public javax.swing.JTabbedPane panelLibranza;
    private javax.swing.JPanel panelUsuario;
    public javax.swing.JTable tblAsesor;
    public javax.swing.JTable tblCampania;
    public javax.swing.JTable tblCampaniaAplicada;
    public javax.swing.JTable tblConsumo;
    public javax.swing.JTable tblGeneral1;
    public javax.swing.JTable tblGeneral2;
    public javax.swing.JTable tblLibranza;
    public javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtAsesorApellidos;
    private javax.swing.JTextField txtAsesorID;
    private javax.swing.JTextField txtAsesorNombres;
    private javax.swing.JTextField txtAsesorSucursal;
    private javax.swing.JTextField txtCampaniaAplicadaAlias;
    private javax.swing.JTextField txtCampaniaAplicadaCod;
    private javax.swing.JTextField txtCampaniaAplicadaFecha;
    private javax.swing.JTextField txtCampaniaAplicadaID;
    private javax.swing.JTextField txtCampaniaDescripcion;
    private javax.swing.JTextField txtCampaniaID;
    private javax.swing.JTextField txtConsumoAsesor;
    private javax.swing.JTextField txtConsumoCuotas;
    private javax.swing.JTextField txtConsumoIDCa;
    private javax.swing.JTextField txtConsumoTasa;
    private javax.swing.JTextField txtLibranzaEmpresa;
    private javax.swing.JTextField txtLibranzaIDCa;
    private javax.swing.JTextField txtLibranzaPlazo;
    private javax.swing.JTextField txtLibranzaTasa;
    private javax.swing.JTextField txtUsuarioAlias;
    private javax.swing.JTextField txtUsuarioApellidos;
    private javax.swing.JTextField txtUsuarioCelular;
    private javax.swing.JTextField txtUsuarioContrasena;
    private javax.swing.JTextField txtUsuarioEmail;
    private javax.swing.JTextField txtUsuarioFecha;
    private javax.swing.JTextField txtUsuarioNombres;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/icon.png")));
    }
    
    public void iniciarVista() {

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }

        

        this.tblResultadosUsuaros = tblUsuario;
        this.tblResultadoscampania = tblCampania;
        this.tblResultadoscampaniasAplicadas = tblCampaniaAplicada;
        this.tblResultadoConsumo = tblConsumo;
        this.tblResultadoAsesor = tblAsesor;
        this.tblResultadolibraza = tblLibranza;
        this.tblResultadoGeneral = tblGeneral1;
        this.tblResultadoGeneral2 = tblGeneral2;
        
        InitialData initialData = new InitialData();
        
        this.setTblResultadosGeneral2(initialData.getConsultaLibranza());
        this.setTblResultadosGeneral(initialData.getConsultaConsumo());
        this.setTblResultadosConsumo(initialData.getConsumos());
        this.setTblResultadosCampanias(initialData.getCampanias());
        this.setTblResultadosCampaniasAplicadas(initialData.getCampaniasAplicadas());
        this.setTblResultadosUsuario(initialData.getUsuarios());
        this.setTblResultadosAsesor(initialData.getAsesores());
        this.setTblResultadoslibranza(initialData.getLibranzas());
    }

    public void setTblResultadosUsuario(ArrayList<UsuarioModelBL> usuarioModelBLs) {
        String[] headers = {"Alias", "Nombre", "Apellido", "Email", "Celular", "Clave", "Fecha de nacimiento"};
        this.tblResultadosUsuaros.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadosUsuaros.setModel(tableModel);
        for (int i = 0; i < usuarioModelBLs.size(); i++) {
            tableModel.addRow(usuarioModelBLs.get(i).toArray());
        }
    }

    public void setTblResultadosCampanias(ArrayList<Campania> campanias) {
        String[] headers = {"ID", "DESCRIPCION"};
        this.tblResultadoscampania.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoscampania.setModel(tableModel);
        for (int i = 0; i < campanias.size(); i++) {
            tableModel.addRow(campanias.get(i).toArray());
        }
    }

    public void setTblResultadosCampaniasAplicadas(ArrayList<CampaniaAplicada> campaniaAplicadas) {
        String[] headers = {"CRÉDITO No.", "NOMBRE DEL CLIENTE", "CAMPAÑA DESCRISCION", "FECHA DE APLICACION", "ID CAMPAÑA", "ALIAS USARIO"};
        this.tblResultadoscampaniasAplicadas.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoscampaniasAplicadas.setModel(tableModel);
        for (int i = 0; i < campaniaAplicadas.size(); i++) {
            tableModel.addRow(campaniaAplicadas.get(i).toArray());
        }
    }

    public void setTblResultadosConsumo(ArrayList<Consumo> consumos) {
        String[] headers = {"ID", "DESCRIPCION DE CAMPAÑA", "CUOTAS", "TASA DE INTERES", "NOMBRE DEL ASESOR", "ID ASESOR", "ID CAMPAÑIA"};
        this.tblResultadoConsumo.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoConsumo.setModel(tableModel);
        for (int i = 0; i < consumos.size(); i++) {
            tableModel.addRow(consumos.get(i).toArray());
        }
    }

    public void setTblResultadosAsesor(ArrayList<AsesorComercial> asesorComercials) {
        String[] headers = {"ID", "NOMBRE", "APELLIDO", "SURCUSAL BANCARIA"};
        this.tblResultadoAsesor.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoAsesor.setModel(tableModel);
        for (int i = 0; i < asesorComercials.size(); i++) {
            tableModel.addRow(asesorComercials.get(i).toArray());
        }
    }

    public void setTblResultadoslibranza(ArrayList<Libranza> libranzas) {
        String[] headers = {"ID", "DESCRPCION DE CAMPAÑA", "EMPRESA", "MESES DE PLAZO", "TAZA DE INTERES","ID CAMPAÑA"};
        this.tblResultadolibraza.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadolibraza.setModel(tableModel);
        for (int i = 0; i < libranzas.size(); i++) {
            tableModel.addRow(libranzas.get(i).toArray());
        }
    }

    public void setTblResultadosGeneral(ArrayList<CampaniaAplicada> general) {
        String[] headers = {"ID", "NOMBRE DE USUARO", "DESCRPCION DE CAMPAÑA", "NOMBRE DE ASESOR", "FECHA DE APLICACION ", "ALIAS DE USUARIO", "ID CAMPAÑA"};
        this.tblResultadoGeneral.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoGeneral.setModel(tableModel);
        for (int i = 0; i < general.size(); i++) {
            tableModel.addRow(general.get(i).toArrayconsumo());
        }
    }

    public void setTblResultadosGeneral2(ArrayList<CampaniaAplicada> general) {
        String[] headers = {"ID", "NOMBRE DE USUARO", "DESCRPCION DE CAMPAÑA", "EMPREZA", "FECHA DE APLICACION ", "ALIAS DE USUARIO", "ID CAMPAÑA"};
        this.tblResultadoGeneral2.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.tblResultadoGeneral2.setModel(tableModel);
        for (int i = 0; i < general.size(); i++) {
            tableModel.addRow(general.get(i).toArraylibranza());
        }
    }

}
